apiVersion: v1
kind: Service
metadata:
  name: nodered
  labels:
    app: nodered
    tier: nodered
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 1880
    protocol: TCP
    name: http
  selector:
    app: nodered
    tier: nodered
